# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  username: yogi@gcc-dev.org
  password: Fireimpact15!

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: jekyll build
  displayName: 'jekyll build'

- script: 
    az login -u $(username) -p $(password)
  displayName: 'Login'

- script: 
    az storage blob upload-batch --account-name simpleblogstorage -s _site -d '$web' 
  displayName : 'Sync _site'
